package com.alipay.riskops.core.model.domain;

import java.util.Date;

/**
 * @author adam
 * @date 2/6/2026 9:16 PM
 */
public class RiskDecision {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_decision.id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_decision.transaction_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_decision.risk_score_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private String riskScoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_decision.outcome
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private String outcome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_decision.reason
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_decision.threshold_applied
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private String thresholdApplied;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_decision.decided_at
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private Date decidedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_decision.id
     *
     * @return the value of risk_decision.id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_decision.id
     *
     * @param id the value for risk_decision.id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_decision.transaction_id
     *
     * @return the value of risk_decision.transaction_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_decision.transaction_id
     *
     * @param transactionId the value for risk_decision.transaction_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_decision.risk_score_id
     *
     * @return the value of risk_decision.risk_score_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getRiskScoreId() {
        return riskScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_decision.risk_score_id
     *
     * @param riskScoreId the value for risk_decision.risk_score_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setRiskScoreId(String riskScoreId) {
        this.riskScoreId = riskScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_decision.outcome
     *
     * @return the value of risk_decision.outcome
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getOutcome() {
        return outcome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_decision.outcome
     *
     * @param outcome the value for risk_decision.outcome
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_decision.reason
     *
     * @return the value of risk_decision.reason
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_decision.reason
     *
     * @param reason the value for risk_decision.reason
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_decision.threshold_applied
     *
     * @return the value of risk_decision.threshold_applied
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getThresholdApplied() {
        return thresholdApplied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_decision.threshold_applied
     *
     * @param thresholdApplied the value for risk_decision.threshold_applied
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setThresholdApplied(String thresholdApplied) {
        this.thresholdApplied = thresholdApplied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_decision.decided_at
     *
     * @return the value of risk_decision.decided_at
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Date getDecidedAt() {
        return decidedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_decision.decided_at
     *
     * @param decidedAt the value for risk_decision.decided_at
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setDecidedAt(Date decidedAt) {
        this.decidedAt = decidedAt;
    }
}