package com.alipay.riskops.core.model.domain;

import java.util.Date;

/**
 * @author adam
 * @date 26/4/2026 6:57 PM
 */
public class RiskopsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riskops_info.riskops_id
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String riskopsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riskops_info.riskops_name
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String riskopsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riskops_info.riskops_category
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String riskopsCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riskops_info.status
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riskops_info.created_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riskops_info.updated_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riskops_info.riskops_id
     *
     * @return the value of riskops_info.riskops_id
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getRiskopsId() {
        return riskopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riskops_info.riskops_id
     *
     * @param riskopsId the value for riskops_info.riskops_id
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setRiskopsId(String riskopsId) {
        this.riskopsId = riskopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riskops_info.riskops_name
     *
     * @return the value of riskops_info.riskops_name
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getRiskopsName() {
        return riskopsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riskops_info.riskops_name
     *
     * @param riskopsName the value for riskops_info.riskops_name
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setRiskopsName(String riskopsName) {
        this.riskopsName = riskopsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riskops_info.riskops_category
     *
     * @return the value of riskops_info.riskops_category
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getRiskopsCategory() {
        return riskopsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riskops_info.riskops_category
     *
     * @param riskopsCategory the value for riskops_info.riskops_category
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setRiskopsCategory(String riskopsCategory) {
        this.riskopsCategory = riskopsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riskops_info.status
     *
     * @return the value of riskops_info.status
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riskops_info.status
     *
     * @param status the value for riskops_info.status
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riskops_info.created_at
     *
     * @return the value of riskops_info.created_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riskops_info.created_at
     *
     * @param createdAt the value for riskops_info.created_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riskops_info.updated_at
     *
     * @return the value of riskops_info.updated_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riskops_info.updated_at
     *
     * @param updatedAt the value for riskops_info.updated_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}