package com.alipay.riskops.common.service.facade.auto.daointerface;

import com.alipay.riskops.common.service.facade.auto.dataobject.test;
import com.alipay.riskops.common.service.facade.auto.dataobject.testExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface testMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    long countByExample(testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int deleteByExample(testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int insert(test row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int insertSelective(test row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    List<test> selectByExample(testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    test selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int updateByExampleSelective(@Param("row") test row, @Param("example") testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int updateByExample(@Param("row") test row, @Param("example") testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int updateByPrimaryKeySelective(test row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Nov 15 23:45:06 MYT 2025
     */
    int updateByPrimaryKey(test row);
}