package com.alipay.riskops.common.dal.auto.daointerface;

import com.alipay.riskops.common.dal.auto.dataobject.RiskopsInfoDO;
import com.alipay.riskops.common.dal.auto.dataobject.RiskopsInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RiskopsInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    long countByExample(RiskopsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int deleteByExample(RiskopsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int deleteByPrimaryKey(String riskopsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int insert(RiskopsInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int insertSelective(RiskopsInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    List<RiskopsInfoDO> selectByExample(RiskopsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    RiskopsInfoDO selectByPrimaryKey(String riskopsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByExampleSelective(@Param("row") RiskopsInfoDO row, @Param("example") RiskopsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByExample(@Param("row") RiskopsInfoDO row, @Param("example") RiskopsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByPrimaryKeySelective(RiskopsInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByPrimaryKey(RiskopsInfoDO row);
}