package com.alipay.riskops.common.dal.auto.daointerface;

import com.alipay.riskops.common.dal.auto.dataobject.RiskRuleConfigDO;
import com.alipay.riskops.common.dal.auto.dataobject.RiskRuleConfigDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RiskRuleConfigDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    long countByExample(RiskRuleConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int deleteByExample(RiskRuleConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int insert(RiskRuleConfigDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int insertSelective(RiskRuleConfigDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    List<RiskRuleConfigDO> selectByExample(RiskRuleConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    RiskRuleConfigDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByExampleSelective(@Param("row") RiskRuleConfigDO row, @Param("example") RiskRuleConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByExample(@Param("row") RiskRuleConfigDO row, @Param("example") RiskRuleConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByPrimaryKeySelective(RiskRuleConfigDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_rule_config
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByPrimaryKey(RiskRuleConfigDO row);
}