package com.alipay.riskops.common.dal.auto.daointerface;

import com.alipay.riskops.common.dal.auto.dataobject.RiskOpsInfoDO;
import com.alipay.riskops.common.dal.auto.dataobject.RiskOpsInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RiskOpsInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    long countByExample(RiskOpsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int deleteByExample(RiskOpsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int deleteByPrimaryKey(String riskopsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int insert(RiskOpsInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int insertSelective(RiskOpsInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    List<RiskOpsInfoDO> selectByExample(RiskOpsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    RiskOpsInfoDO selectByPrimaryKey(String riskopsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByExampleSelective(@Param("row") RiskOpsInfoDO row, @Param("example") RiskOpsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByExample(@Param("row") RiskOpsInfoDO row, @Param("example") RiskOpsInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByPrimaryKeySelective(RiskOpsInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    int updateByPrimaryKey(RiskOpsInfoDO row);
}