package com.alipay.riskops.common.dal.auto.daointerface;

import com.alipay.riskops.common.dal.auto.dataobject.RiskDecisionDO;
import com.alipay.riskops.common.dal.auto.dataobject.RiskDecisionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RiskDecisionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    long countByExample(RiskDecisionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int deleteByExample(RiskDecisionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int insert(RiskDecisionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int insertSelective(RiskDecisionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    List<RiskDecisionDO> selectByExample(RiskDecisionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    RiskDecisionDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByExampleSelective(@Param("row") RiskDecisionDO row, @Param("example") RiskDecisionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByExample(@Param("row") RiskDecisionDO row, @Param("example") RiskDecisionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByPrimaryKeySelective(RiskDecisionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    int updateByPrimaryKey(RiskDecisionDO row);
}