package com.alipay.riskops.common.dal.auto.daointerface;

import com.alipay.riskops.common.dal.auto.dataobject.RiskScoreDO;
import com.alipay.riskops.common.dal.auto.dataobject.RiskScoreDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RiskScoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    long countByExample(RiskScoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int deleteByExample(RiskScoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int insert(RiskScoreDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int insertSelective(RiskScoreDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    List<RiskScoreDO> selectByExample(RiskScoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    RiskScoreDO selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int updateByExampleSelective(@Param("row") RiskScoreDO row, @Param("example") RiskScoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int updateByExample(@Param("row") RiskScoreDO row, @Param("example") RiskScoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int updateByPrimaryKeySelective(RiskScoreDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    int updateByPrimaryKey(RiskScoreDO row);
}