package com.alipay.riskops.common.dal.auto.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RiskOpsInfoDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public RiskOpsInfoDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRiskOpsIdIsNull() {
            addCriterion("riskops_id is null");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdIsNotNull() {
            addCriterion("riskops_id is not null");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdEqualTo(String value) {
            addCriterion("riskops_id =", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdNotEqualTo(String value) {
            addCriterion("riskops_id <>", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdGreaterThan(String value) {
            addCriterion("riskops_id >", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdGreaterThanOrEqualTo(String value) {
            addCriterion("riskops_id >=", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdLessThan(String value) {
            addCriterion("riskops_id <", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdLessThanOrEqualTo(String value) {
            addCriterion("riskops_id <=", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdLike(String value) {
            addCriterion("riskops_id like", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdNotLike(String value) {
            addCriterion("riskops_id not like", value, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdIn(List<String> values) {
            addCriterion("riskops_id in", values, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdNotIn(List<String> values) {
            addCriterion("riskops_id not in", values, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdBetween(String value1, String value2) {
            addCriterion("riskops_id between", value1, value2, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsIdNotBetween(String value1, String value2) {
            addCriterion("riskops_id not between", value1, value2, "riskopsId");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameIsNull() {
            addCriterion("riskops_name is null");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameIsNotNull() {
            addCriterion("riskops_name is not null");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameEqualTo(String value) {
            addCriterion("riskops_name =", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameNotEqualTo(String value) {
            addCriterion("riskops_name <>", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameGreaterThan(String value) {
            addCriterion("riskops_name >", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameGreaterThanOrEqualTo(String value) {
            addCriterion("riskops_name >=", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameLessThan(String value) {
            addCriterion("riskops_name <", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameLessThanOrEqualTo(String value) {
            addCriterion("riskops_name <=", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameLike(String value) {
            addCriterion("riskops_name like", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameNotLike(String value) {
            addCriterion("riskops_name not like", value, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameIn(List<String> values) {
            addCriterion("riskops_name in", values, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameNotIn(List<String> values) {
            addCriterion("riskops_name not in", values, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameBetween(String value1, String value2) {
            addCriterion("riskops_name between", value1, value2, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsNameNotBetween(String value1, String value2) {
            addCriterion("riskops_name not between", value1, value2, "riskopsName");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryIsNull() {
            addCriterion("riskops_category is null");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryIsNotNull() {
            addCriterion("riskops_category is not null");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryEqualTo(String value) {
            addCriterion("riskops_category =", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryNotEqualTo(String value) {
            addCriterion("riskops_category <>", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryGreaterThan(String value) {
            addCriterion("riskops_category >", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("riskops_category >=", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryLessThan(String value) {
            addCriterion("riskops_category <", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryLessThanOrEqualTo(String value) {
            addCriterion("riskops_category <=", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryLike(String value) {
            addCriterion("riskops_category like", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryNotLike(String value) {
            addCriterion("riskops_category not like", value, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryIn(List<String> values) {
            addCriterion("riskops_category in", values, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryNotIn(List<String> values) {
            addCriterion("riskops_category not in", values, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryBetween(String value1, String value2) {
            addCriterion("riskops_category between", value1, value2, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andRiskOpsCategoryNotBetween(String value1, String value2) {
            addCriterion("riskops_category not between", value1, value2, "riskopsCategory");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table riskops_info
     *
     * @mbg.generated do_not_delete_during_merge Mon May 04 15:02:00 AEST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table riskops_info
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}