package com.alipay.riskops.common.dal.auto.dataobject;

import java.util.Date;

public class RiskScoreDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_score.id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_score.transaction_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private Object transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_score.score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private Short score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_score.signals
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private Object signals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_score.calculated_at
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    private Date calculatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_score.id
     *
     * @return the value of risk_score.id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_score.id
     *
     * @param id the value for risk_score.id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_score.transaction_id
     *
     * @return the value of risk_score.transaction_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Object getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_score.transaction_id
     *
     * @param transactionId the value for risk_score.transaction_id
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setTransactionId(Object transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_score.score
     *
     * @return the value of risk_score.score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Short getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_score.score
     *
     * @param score the value for risk_score.score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setScore(Short score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_score.signals
     *
     * @return the value of risk_score.signals
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Object getSignals() {
        return signals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_score.signals
     *
     * @param signals the value for risk_score.signals
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setSignals(Object signals) {
        this.signals = signals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_score.calculated_at
     *
     * @return the value of risk_score.calculated_at
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Date getCalculatedAt() {
        return calculatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_score.calculated_at
     *
     * @param calculatedAt the value for risk_score.calculated_at
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setCalculatedAt(Date calculatedAt) {
        this.calculatedAt = calculatedAt;
    }
}