package com.alipay.riskops.common.dal.auto.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RiskDecisionDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public RiskDecisionDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(String value) {
            addCriterion("transaction_id =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(String value) {
            addCriterion("transaction_id <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(String value) {
            addCriterion("transaction_id >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_id >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(String value) {
            addCriterion("transaction_id <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("transaction_id <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLike(String value) {
            addCriterion("transaction_id like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotLike(String value) {
            addCriterion("transaction_id not like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<String> values) {
            addCriterion("transaction_id in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<String> values) {
            addCriterion("transaction_id not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(String value1, String value2) {
            addCriterion("transaction_id between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(String value1, String value2) {
            addCriterion("transaction_id not between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdIsNull() {
            addCriterion("risk_score_id is null");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdIsNotNull() {
            addCriterion("risk_score_id is not null");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdEqualTo(String value) {
            addCriterion("risk_score_id =", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdNotEqualTo(String value) {
            addCriterion("risk_score_id <>", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdGreaterThan(String value) {
            addCriterion("risk_score_id >", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("risk_score_id >=", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdLessThan(String value) {
            addCriterion("risk_score_id <", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdLessThanOrEqualTo(String value) {
            addCriterion("risk_score_id <=", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdLike(String value) {
            addCriterion("risk_score_id like", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdNotLike(String value) {
            addCriterion("risk_score_id not like", value, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdIn(List<String> values) {
            addCriterion("risk_score_id in", values, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdNotIn(List<String> values) {
            addCriterion("risk_score_id not in", values, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdBetween(String value1, String value2) {
            addCriterion("risk_score_id between", value1, value2, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIdNotBetween(String value1, String value2) {
            addCriterion("risk_score_id not between", value1, value2, "riskScoreId");
            return (Criteria) this;
        }

        public Criteria andOutcomeIsNull() {
            addCriterion("outcome is null");
            return (Criteria) this;
        }

        public Criteria andOutcomeIsNotNull() {
            addCriterion("outcome is not null");
            return (Criteria) this;
        }

        public Criteria andOutcomeEqualTo(String value) {
            addCriterion("outcome =", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeNotEqualTo(String value) {
            addCriterion("outcome <>", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeGreaterThan(String value) {
            addCriterion("outcome >", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeGreaterThanOrEqualTo(String value) {
            addCriterion("outcome >=", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeLessThan(String value) {
            addCriterion("outcome <", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeLessThanOrEqualTo(String value) {
            addCriterion("outcome <=", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeLike(String value) {
            addCriterion("outcome like", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeNotLike(String value) {
            addCriterion("outcome not like", value, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeIn(List<String> values) {
            addCriterion("outcome in", values, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeNotIn(List<String> values) {
            addCriterion("outcome not in", values, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeBetween(String value1, String value2) {
            addCriterion("outcome between", value1, value2, "outcome");
            return (Criteria) this;
        }

        public Criteria andOutcomeNotBetween(String value1, String value2) {
            addCriterion("outcome not between", value1, value2, "outcome");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("reason is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("reason is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("reason =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("reason <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("reason >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reason >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("reason <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("reason <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("reason like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("reason not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("reason in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("reason not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("reason between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("reason not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedIsNull() {
            addCriterion("threshold_applied is null");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedIsNotNull() {
            addCriterion("threshold_applied is not null");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedEqualTo(String value) {
            addCriterion("threshold_applied =", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedNotEqualTo(String value) {
            addCriterion("threshold_applied <>", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedGreaterThan(String value) {
            addCriterion("threshold_applied >", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedGreaterThanOrEqualTo(String value) {
            addCriterion("threshold_applied >=", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedLessThan(String value) {
            addCriterion("threshold_applied <", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedLessThanOrEqualTo(String value) {
            addCriterion("threshold_applied <=", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedLike(String value) {
            addCriterion("threshold_applied like", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedNotLike(String value) {
            addCriterion("threshold_applied not like", value, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedIn(List<String> values) {
            addCriterion("threshold_applied in", values, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedNotIn(List<String> values) {
            addCriterion("threshold_applied not in", values, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedBetween(String value1, String value2) {
            addCriterion("threshold_applied between", value1, value2, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andThresholdAppliedNotBetween(String value1, String value2) {
            addCriterion("threshold_applied not between", value1, value2, "thresholdApplied");
            return (Criteria) this;
        }

        public Criteria andDecidedAtIsNull() {
            addCriterion("decided_at is null");
            return (Criteria) this;
        }

        public Criteria andDecidedAtIsNotNull() {
            addCriterion("decided_at is not null");
            return (Criteria) this;
        }

        public Criteria andDecidedAtEqualTo(Date value) {
            addCriterion("decided_at =", value, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtNotEqualTo(Date value) {
            addCriterion("decided_at <>", value, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtGreaterThan(Date value) {
            addCriterion("decided_at >", value, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("decided_at >=", value, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtLessThan(Date value) {
            addCriterion("decided_at <", value, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtLessThanOrEqualTo(Date value) {
            addCriterion("decided_at <=", value, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtIn(List<Date> values) {
            addCriterion("decided_at in", values, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtNotIn(List<Date> values) {
            addCriterion("decided_at not in", values, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtBetween(Date value1, Date value2) {
            addCriterion("decided_at between", value1, value2, "decidedAt");
            return (Criteria) this;
        }

        public Criteria andDecidedAtNotBetween(Date value1, Date value2) {
            addCriterion("decided_at not between", value1, value2, "decidedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_decision
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 02 21:10:22 AEST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_decision
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}