package com.alipay.riskops.common.dal.auto.dataobject;

import java.util.Date;

public class RiskRuleConfigDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.id
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.rule_code
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private String ruleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.signal_type
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private String signalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.score
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.weight
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.enabled
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.config_json
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private Object configJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.description
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.created_at
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_rule_config.updated_at
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.id
     *
     * @return the value of risk_rule_config.id
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.id
     *
     * @param id the value for risk_rule_config.id
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.rule_code
     *
     * @return the value of risk_rule_config.rule_code
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public String getRuleCode() {
        return ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.rule_code
     *
     * @param ruleCode the value for risk_rule_config.rule_code
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.signal_type
     *
     * @return the value of risk_rule_config.signal_type
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public String getSignalType() {
        return signalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.signal_type
     *
     * @param signalType the value for risk_rule_config.signal_type
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setSignalType(String signalType) {
        this.signalType = signalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.score
     *
     * @return the value of risk_rule_config.score
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.score
     *
     * @param score the value for risk_rule_config.score
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.weight
     *
     * @return the value of risk_rule_config.weight
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.weight
     *
     * @param weight the value for risk_rule_config.weight
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.enabled
     *
     * @return the value of risk_rule_config.enabled
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.enabled
     *
     * @param enabled the value for risk_rule_config.enabled
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.config_json
     *
     * @return the value of risk_rule_config.config_json
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public Object getConfigJson() {
        return configJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.config_json
     *
     * @param configJson the value for risk_rule_config.config_json
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setConfigJson(Object configJson) {
        this.configJson = configJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.description
     *
     * @return the value of risk_rule_config.description
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.description
     *
     * @param description the value for risk_rule_config.description
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.created_at
     *
     * @return the value of risk_rule_config.created_at
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.created_at
     *
     * @param createdAt the value for risk_rule_config.created_at
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_rule_config.updated_at
     *
     * @return the value of risk_rule_config.updated_at
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_rule_config.updated_at
     *
     * @param updatedAt the value for risk_rule_config.updated_at
     *
     * @mbg.generated Fri Jun 12 22:41:15 AEST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}