package com.alipay.riskops.common.dal.auto.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RiskScoreDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public RiskScoreDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Object value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Object value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Object value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Object value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Object value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Object value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Object> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Object> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Object value1, Object value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Object value1, Object value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(Object value) {
            addCriterion("transaction_id =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(Object value) {
            addCriterion("transaction_id <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(Object value) {
            addCriterion("transaction_id >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(Object value) {
            addCriterion("transaction_id >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(Object value) {
            addCriterion("transaction_id <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(Object value) {
            addCriterion("transaction_id <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<Object> values) {
            addCriterion("transaction_id in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<Object> values) {
            addCriterion("transaction_id not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(Object value1, Object value2) {
            addCriterion("transaction_id between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(Object value1, Object value2) {
            addCriterion("transaction_id not between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Short value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Short value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Short value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Short value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Short value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Short value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Short> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Short> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Short value1, Short value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Short value1, Short value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andSignalsIsNull() {
            addCriterion("signals is null");
            return (Criteria) this;
        }

        public Criteria andSignalsIsNotNull() {
            addCriterion("signals is not null");
            return (Criteria) this;
        }

        public Criteria andSignalsEqualTo(Object value) {
            addCriterion("signals =", value, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsNotEqualTo(Object value) {
            addCriterion("signals <>", value, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsGreaterThan(Object value) {
            addCriterion("signals >", value, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsGreaterThanOrEqualTo(Object value) {
            addCriterion("signals >=", value, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsLessThan(Object value) {
            addCriterion("signals <", value, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsLessThanOrEqualTo(Object value) {
            addCriterion("signals <=", value, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsIn(List<Object> values) {
            addCriterion("signals in", values, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsNotIn(List<Object> values) {
            addCriterion("signals not in", values, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsBetween(Object value1, Object value2) {
            addCriterion("signals between", value1, value2, "signals");
            return (Criteria) this;
        }

        public Criteria andSignalsNotBetween(Object value1, Object value2) {
            addCriterion("signals not between", value1, value2, "signals");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtIsNull() {
            addCriterion("calculated_at is null");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtIsNotNull() {
            addCriterion("calculated_at is not null");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtEqualTo(Date value) {
            addCriterion("calculated_at =", value, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtNotEqualTo(Date value) {
            addCriterion("calculated_at <>", value, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtGreaterThan(Date value) {
            addCriterion("calculated_at >", value, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("calculated_at >=", value, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtLessThan(Date value) {
            addCriterion("calculated_at <", value, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtLessThanOrEqualTo(Date value) {
            addCriterion("calculated_at <=", value, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtIn(List<Date> values) {
            addCriterion("calculated_at in", values, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtNotIn(List<Date> values) {
            addCriterion("calculated_at not in", values, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtBetween(Date value1, Date value2) {
            addCriterion("calculated_at between", value1, value2, "calculatedAt");
            return (Criteria) this;
        }

        public Criteria andCalculatedAtNotBetween(Date value1, Date value2) {
            addCriterion("calculated_at not between", value1, value2, "calculatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_score
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 02 21:10:22 AEST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_score
     *
     * @mbg.generated Tue Jun 02 21:10:22 AEST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}